version: '3.3'
services:
  agent_parent:
    image: netdata/netdata:latest
    container_name: parent
    ports:
      - 20000:19999
    volumes:
      - ./parent_stream.conf:/etc/netdata/stream.conf:ro
    environment:
      - NETDATA_CLAIM_TOKEN=${CLAIM_TOKEN_PARENT_SPACE}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
  agent_child1:
    image: netdata/netdata:latest
    container_name: child1
    ports:
    - 20001:19999
    volumes:
      - ./child_stream.conf:/etc/netdata/stream.conf:ro
    environment:
      - NETDATA_CLAIM_TOKEN=${CLAIM_TOKEN_CHILD_SPACE}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
  agent_child2:
    image: netdata/netdata:latest
    container_name: child2
    ports:
    - 20002:19999
    volumes:
      - ./child_stream.conf:/etc/netdata/stream.conf:ro
    environment:
      - NETDATA_CLAIM_TOKEN=${CLAIM_TOKEN_CHILD_SPACE}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
